rd LstFlash /s/q
rd LstFlashIAP /s/q
rd LstRAM /s/q
rd LstSim /s/q
rd ObjFlash /s/q
rd ObjFlashIAP /s/q
rd ObjRAM /s/q
rd ObjSim /s/q
del *.bak /s
del *.ddk /s
del *.edk /s
del *.lst /s
del *.lnp /s
del *.mpf /s
del *.mpj /s
del *.obj /s
del *.omf /s
del *.opt /s
del *.plg /s
del *.rpt /s
del *.tmp /s
del *.__i /s
del *.crf /s
del *.o /s
del *.d /s
del *.axf /s
del *.tra /s
del *.dep /s
del JLinkLog.txt /s
exit
